### ISSUE TITLE
Subscribing to server calls on client not working?

### ISSUE THREAD

**Issue by josdeweger-zz** [jmichas/SignalRF#1]
Hi jmichas,

first off: great work on porting the client to Actionscript! We are looking for a proper way to connect our flash desktop application (mdm zinc) to signalr, and this might just do the trick!

However, I have a problem using the .on method on the HubProxy. Invoking a method works just fine, but subscribing to a server call to the client doesn't seem to trigger the callback function. I used your example code to create the following:

_ChatHub.on("broadcastMessage", Message, function(model:Message):void {
    trace("Message by: " + model.Name);
    trace("Text: " + model.Text);
});

In my output window I get:
[22-2-2014 12:53:26] SignalR: WebSocketEvent.MESSAGE {"C":"d-1B684D93-B,D|d,0|e,1|f,0","M":[{"H":"ChatHub","M":"broadcastMessage","A":[{"Name":"sam","Text":"my message"}]}]}

But I don't see the trace messages. What am I missing here?
A second question related to this: if I want to invoke a method on the client without any params, can I just pass null as the Type 'T', like this:

_ChatHub.on("myMethod", null, function():void {
    trace("myMethod called!");
});

this doesn't seem to work as well.

Hoping you can shed some light on this.

cheers!

**Comment by jmichas** [comment]
Hi samuraipizzacat,

Thanks, Im glad you are liking things so far.

Unfortunately you caught me at a bad time. My main development laptop just died yesterday so Im not able to get to my sample projects that I developed with so Im going to do some creative guessing here to try and help.

For the first problem, does your Message object in AS extend the SignalRObject? Its in com.michas.signalRF. types. It needs to if it doesn’t, the SignalRFObject contains the code used to parse the returned response from the server into a typed AS3 object. The parse function can be overridden if your server side object contains complex properties. Look at the src for SignalRFObject.

For your second question, I am not sure off hand. If I had my laptop running I could easily test, but for now Im in the dark. But, if you get the first problem fixed, maybe create a dummy object that extends SignalRFObject and use that instead of null.

If you continue to have trouble try to use the source in your project and debug. The code that parses the returned server response is in hubs/Subscription.as. You can set some break points and see if the data is getting parsed properly. I had issues at first with date types from the server since they come down in some formats not easily parsed in AS3.
You could also set break points in the parse function in SignalRFObject to see if it is failing on a particular property.

If you fork the project and find/fix any bugs be sure to do a pull request so I can bring them back into the main project.

How’d did you find the project BTW?

I hope this helps, let me know what you find out.

Thanks,
Jason

P.S. So I was proofreading and making sure what I was telling you was as accurate as could be. I was looking at the subscription.as file. I think I see what the problem may be. If you see that received() on line 50 is only called when the object returned is an array. So if your message coming from the server is a single object the callback may never fire. It would be great if you could confirm that this is the problem. I can’t fix or test right now so, let me know.

**Comment by josdeweger-zz** [comment]
Hi Jason,

A quick and great response, thanks! And I know what it feels like to have your dev laptop die on you, happened to me a couple of weeks ago. Frustrating. So good luck with that :)

The object Message i'm using is extending the SignalRObject. (As you can see im doing the cliché chat thingy as a testproject).

So I tried to return an array of Messages (Message[]) from the server, but the result is I get the following trace:
 [22-2-2014 16:07:39] SignalR: WebSocketEvent.MESSAGE {"C":"d-93DA799-B,2|L,0|M,1|N,0","M":[{"H":"ChatHub","M":"broadcastMessage","A":[[{"Name":"sam","Text":"adfsdf"}]]}]}

The callback function is not hit. When you look at the json, you can see that the response is now wrapped in 2 arrays, so i'm guessing that's not the answer to my problem, because the response was already wrapped in an array. I tried walking through the code with the debugger to see what is happening, but there is too much going on that I do not understand (my Actionscript knowledge is limited). The onReceived function in Subscription.as is never hit as far as I can tell.

If you'd like I could send you my test project(s), server and client (flashdevelop)? I think it might be a matter of adding some code to check for a single object in the array, if so, check to see whether that object is of type 'T' and if there is a subscription that matches that signature?

One other question: will I be able to use the src/swc on a flash application? It is not air/flex, so I think there may lie a couple of problems too, right? (again, limited knowledge there...) If there is work to be done, can you point me in the right direction (where to start, good docs/tuts)? I would be happy to submit my changes if they are relevant to you.

I found the repo via stackoverflow (what else ;)) - http://stackoverflow.com/a/21057089

Cheers!

Sam

**Comment by jmichas** [comment]
Sam,

Thanks. If you sent me stuff I couldn’t test anyway, I don’t have any tools installed on the machine Im borrowing at the moment.

But try this, in subscription.as set breakpoints at line 26,28 and 50 those are the lines where the On callback will be triggered.
You should be able to get an idea of whether its a problem with the returned object getting parsed or something further up stream.

The trace message you see is the raw response from the server coming over the socket.

I have a feeling the problem is in the object being parsed and maybe the error is getting swallowed in the try catch block in subscription.

Damn, wish I had a way to work, Im sure I could figure this out in a few minutes.

Thanks,
Jason

**Comment by jmichas** [comment]
Sorry, I forgot to answer your other question, Im frantically multi tasking to get my drive backed up before I bring my machine to apple.

Im not sure about using the swc in a flash app. I can’t say whether it would or wouldn’t work, Ive never tried. I develop in flash builder/flex predominantly.

**Comment by josdeweger-zz** [comment]
Hi Jason,

could not resist to do some more digging. I found the problem and was able to solve it (hurray!)
The problem was that there was no match found on the hubname in the HubConnection.as class. 

As you are supposed to on the Javascript client, I started the hubname lowercase. Since the connection and sending of messages worked, I assumed this was correct. But HubConnection.as around line 100 expected first letter to be upper case. 

I did a 'fix' where I compare the key in the dictionary against the invocation.hub string. I added a new DictionaryHelper in the utils folder. If you want I could fork the repository so you can see what I mean (haven't done much on Github, but i'll probably manage). For now:

HubConnection.as from line 99:

```
       var hubName:String = new DictionaryHelpers().SearchForKeyCaseInsensitive(_hubs, invocation.hub);

            if (_hubs[hubName]!=null)
            {
                hubProxy = _hubs[hubName];
                if (invocation.state != null)
                {
                    for each (var key:Object in invocation.state)
                    {
                        hubProxy[key] = invocation.state[key];
                    }
                }

                hubProxy.invokeEvent(invocation.method, invocation.args);
            }
```

New class DictionaryHelpers in utils folder:

```
    public class DictionaryHelpers 
{

    public function DictionaryHelpers() 
    {

    }

    /**
     * Searches through the keys of a dictionary and returns that key if it exists
     */
    public function SearchForKeyCaseInsensitive(dict:Dictionary, inputString:String) : String
    {
        for (var key:String in dict)
        {
            var valueStringToLower:String = key.toLowerCase();
            var inputStringToLower:String = inputString.toLowerCase();

            if (valueStringToLower == inputStringToLower)
                return key;
        }

        return null;
    }
}
```

This AS3 syntax is coming back to me... ;)

**Comment by jmichas** [comment]
Okay, cool, Im glad you found a solution.
I think that the reason I didn’t check for init caps for hub key is that in SignalR on the server side there is a configuration option you can do for the json serializer so that it uses camel case. This way if your c# hub is called ChatHub, when it gets serialized it should be chatHub, then on the AS3 side when you create the hub you would use signalRF.createHubProxy(“chatHub”). 

But, your fix should probably be included incase people don’t like the camel case option.

Yeah, if its not too much trouble, fork the project and put your fix in and I can pull them in. The more people using this in different projects the quicker we can find little quirks and bugs like this. I should update the example code on github to state that you should set the serializer on the server to camel case.

Thanks,
Jason

**Comment by zawarski** [comment]
It works fine in Flash, but you have to make a change to TaskInterop.as. Add:
import flash.system.Capabilities;
And then in loadText(), change:
req.idleTimeout = timeoutMilliseconds;
To:
if (Capabilities.playerType == 'Desktop') {
    req.idleTimeout = timeoutMilliseconds;
}
